In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)

plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False

# 主样本表：后面 Logit 建模主要用这张
sample_7d = pd.read_csv(
    'step2_click_sample_labeled_7d.csv',
    parse_dates=['click_date', 'first_click_ts', 'last_click_ts', 'order_time'],
    low_memory=False
)

# 描述统计结果表：后面解释结果时会用到
channel_summary = pd.read_csv('step3_channel_summary.csv', low_memory=False)
click_bucket_summary = pd.read_csv('step3_click_bucket_summary.csv', low_memory=False)
focus_summary = pd.read_csv('step3_focus_summary.csv', low_memory=False)
channel_type_summary = pd.read_csv('step3_channel_type_summary.csv', low_memory=False)

channel_clickcnt_summary = pd.read_csv('step3_channel_clickcnt_summary.csv', low_memory=False)
channel_clickcnt_pivot = pd.read_csv('step3_channel_clickcnt_pivot.csv', low_memory=False)

channel_focus_summary = pd.read_csv('step3_channel_focus_summary.csv', low_memory=False)
channel_focus_pivot = pd.read_csv('step3_channel_focus_pivot.csv', low_memory=False)

print('sample_7d:', sample_7d.shape)
print('channel_summary:', channel_summary.shape)
print('click_bucket_summary:', click_bucket_summary.shape)
print('focus_summary:', focus_summary.shape)
print('channel_type_summary:', channel_type_summary.shape)
print('channel_clickcnt_summary:', channel_clickcnt_summary.shape)
print('channel_clickcnt_pivot:', channel_clickcnt_pivot.shape)
print('channel_focus_summary:', channel_focus_summary.shape)
print('channel_focus_pivot:', channel_focus_pivot.shape)

sample_7d: (213050, 41)
channel_summary: (5, 9)
click_bucket_summary: (6, 3)
focus_summary: (2, 5)
channel_type_summary: (10, 6)
channel_clickcnt_summary: (30, 7)
channel_clickcnt_pivot: (6, 6)
channel_focus_summary: (10, 7)
channel_focus_pivot: (5, 4)

In [3]:
model_df = sample_7d.copy()

# 只保留第一版建模最核心的变量
model_df = model_df[
    [
        'label_7d',
        'channel',
        'type',
        'sku_focus_flag',
        'repeat_same_sku_flag',
        'click_cnt',
        'user_day_distinct_skus',
        'user_day_distinct_channels',
        'is_plus',
        'purchase_power',
        'city_level',
        'gender',
        'age'
    ]
].copy()

# 删除关键变量缺失值
model_df = model_df.dropna().copy()

print(model_df.shape)
model_df.head()

(213050, 13)

,label_7d,channel,type,sku_focus_flag,repeat_same_sku_flag,click_cnt,user_day_distinct_skus,user_day_distinct_channels,is_plus,purchase_power,city_level,gender,age
0,1,app,1,0,0,1,2,1,1,2,1,F,26-35
1,0,app,2,1,0,1,1,1,0,2,4,F,26-35
2,0,app,1,1,0,1,1,1,1,2,4,F,26-35
3,0,app,2,1,0,1,1,1,0,3,1,M,16-25
4,1,app,1,0,0,1,2,1,0,4,4,M,26-35

In [4]:
model1 = smf.logit(
    'label_7d ~ C(channel)',
    data=model_df
).fit()

print(model1.summary())

Optimization terminated successfully.
         Current function value: 0.402425
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:               label_7d   No. Observations:               213050
Model:                          Logit   Df Residuals:                   213045
Method:                           MLE   Df Model:                            4
Date:                Mon, 13 Apr 2026   Pseudo R-squ.:                0.003054
Time:                        11:47:53   Log-Likelihood:                -85737.
converged:                       True   LL-Null:                       -85999.
Covariance Type:            nonrobust   LLR p-value:                2.233e-112
========================================================================================
                           coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept               -1.8582      0.007   -268.024      0.000      -1.872      -1.845
C(channel)[T.mobile]     0.6295      0.039     15.975      0.000       0.552       0.707
C(channel)[T.others]     0.2336      0.054      4.329      0.000       0.128       0.339
C(channel)[T.pc]         0.4403      0.025     17.413      0.000       0.391       0.490
C(channel)[T.wechat]    -0.0690      0.024     -2.920      0.004      -0.115      -0.023
========================================================================================

In [10]:
model2_fix = smf.logit(
    "label_7d ~ C(channel, Treatment(reference='app')) + C(type) + is_plus + C(purchase_power) + C(city_level) + C(gender) + C(age)",
    data=model_df
).fit(method='lbfgs', maxiter=200)

print(model2_fix.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:               label_7d   No. Observations:               213050
Model:                          Logit   Df Residuals:                   213025
Method:                           MLE   Df Model:                           24
Date:                Mon, 13 Apr 2026   Pseudo R-squ.:                 0.01397
Time:                        12:11:36   Log-Likelihood:                -84798.
converged:                       True   LL-Null:                       -85999.
Covariance Type:            nonrobust   LLR p-value:                     0.000
====================================================================================================================
                                                       coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------
Intercept                                           -1.7462      0.037    -47.830      0.000      -1.818      -1.675
C(channel, Treatment(reference='app'))[T.mobile]     0.6248      0.040     15.700      0.000       0.547       0.703
C(channel, Treatment(reference='app'))[T.others]     0.3630      0.055      6.617      0.000       0.255       0.471
C(channel, Treatment(reference='app'))[T.pc]         0.3590      0.026     13.940      0.000       0.308       0.409
C(channel, Treatment(reference='app'))[T.wechat]     0.0441      0.027      1.637      0.102      -0.009       0.097
C(type)[T.2]                                        -0.5472      0.014    -38.474      0.000      -0.575      -0.519
C(purchase_power)[T.1]                               0.0726      0.059      1.228      0.220      -0.043       0.189
C(purchase_power)[T.2]                              -0.1021      0.028     -3.686      0.000      -0.156      -0.048
C(purchase_power)[T.3]                              -0.1334      0.029     -4.616      0.000      -0.190      -0.077
C(purchase_power)[T.4]                               0.0620      0.052      1.188      0.235      -0.040       0.164
C(purchase_power)[T.5]                               0.4508      0.312      1.446      0.148      -0.160       1.062
C(city_level)[T.1]                                   0.1522      0.029      5.285      0.000       0.096       0.209
C(city_level)[T.2]                                   0.0411      0.028      1.476      0.140      -0.013       0.096
C(city_level)[T.3]                                   0.0408      0.031      1.327      0.185      -0.019       0.101
C(city_level)[T.4]                                  -0.0323      0.031     -1.030      0.303      -0.094       0.029
C(city_level)[T.5]                                   0.0978      0.061      1.617      0.106      -0.021       0.216
C(gender)[T.M]                                       0.0163      0.016      1.000      0.317      -0.016       0.048
C(gender)[T.U]                                       0.2140      0.181      1.183      0.237      -0.141       0.569
C(age)[T.26-35]                                      0.1666      0.016     10.183      0.000       0.135       0.199
C(age)[T.36-45]                                      0.2047      0.020     10.294      0.000       0.166       0.244
C(age)[T.46-55]                                      0.1682      0.036      4.610      0.000       0.097       0.240
C(age)[T.<=15]                                      -0.1995      0.914     -0.218      0.827      -1.990       1.591
C(age)[T.>=56]                                       0.1820      0.044      4.125      0.000       0.096       0.269
C(age)[T.U]                                         -0.1889      0.185     -1.024      0.306      -0.551       0.173
is_plus                                             -0.0860      0.016     -5.533      0.000      -0.116      -0.056
====================================================================================================================

In [11]:
base_formula = (
    "label_7d ~ "
    "C(channel, Treatment(reference='app')) + "
    "C(type) + is_plus + "
    "C(purchase_power) + C(city_level) + "
    "C(gender) + C(age)"
)

m3_a = smf.logit(
    base_formula + " + sku_focus_flag",
    data=model_df
).fit(method='lbfgs', maxiter=300)

m3_b = smf.logit(
    base_formula + " + repeat_same_sku_flag",
    data=model_df
).fit(method='lbfgs', maxiter=300)

m3_c = smf.logit(
    base_formula + " + click_cnt",
    data=model_df
).fit(method='lbfgs', maxiter=300)

m3_d = smf.logit(
    base_formula + " + user_day_distinct_skus",
    data=model_df
).fit(method='lbfgs', maxiter=300)

m3_e = smf.logit(
    base_formula + " + user_day_distinct_channels",
    data=model_df
).fit(method='lbfgs', maxiter=300)

print('m3_a converged =', m3_a.mle_retvals['converged'])
print('m3_b converged =', m3_b.mle_retvals['converged'])
print('m3_c converged =', m3_c.mle_retvals['converged'])
print('m3_d converged =', m3_d.mle_retvals['converged'])
print('m3_e converged =', m3_e.mle_retvals['converged'])

m3_a converged = True
m3_b converged = True
m3_c converged = True
m3_d converged = True
m3_e converged = True

In [12]:
model3_focus = smf.logit(
    base_formula + " + sku_focus_flag + user_day_distinct_skus",
    data=model_df
).fit(method='lbfgs', maxiter=300)

print(model3_focus.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:               label_7d   No. Observations:               213050
Model:                          Logit   Df Residuals:                   213023
Method:                           MLE   Df Model:                           26
Date:                Mon, 13 Apr 2026   Pseudo R-squ.:                  0.1051
Time:                        12:20:16   Log-Likelihood:                -76964.
converged:                       True   LL-Null:                       -85999.
Covariance Type:            nonrobust   LLR p-value:                     0.000
====================================================================================================================
                                                       coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------
Intercept                                           -1.6862      0.041    -41.455      0.000      -1.766      -1.607
C(channel, Treatment(reference='app'))[T.mobile]     0.5957      0.042     14.228      0.000       0.514       0.678
C(channel, Treatment(reference='app'))[T.others]     0.5582      0.058      9.662      0.000       0.445       0.671
C(channel, Treatment(reference='app'))[T.pc]         0.5346      0.027     19.739      0.000       0.482       0.588
C(channel, Treatment(reference='app'))[T.wechat]     0.0857      0.028      3.056      0.002       0.031       0.141
C(type)[T.2]                                        -0.4313      0.015    -29.146      0.000      -0.460      -0.402
C(purchase_power)[T.1]                               0.0628      0.062      1.015      0.310      -0.059       0.184
C(purchase_power)[T.2]                              -0.1108      0.029     -3.827      0.000      -0.168      -0.054
C(purchase_power)[T.3]                              -0.0879      0.030     -2.906      0.004      -0.147      -0.029
C(purchase_power)[T.4]                               0.0170      0.055      0.312      0.755      -0.090       0.124
C(purchase_power)[T.5]                               0.1937      0.325      0.596      0.551      -0.444       0.831
C(city_level)[T.1]                                   0.1004      0.030      3.336      0.001       0.041       0.159
C(city_level)[T.2]                                   0.0202      0.029      0.693      0.488      -0.037       0.077
C(city_level)[T.3]                                  -0.0259      0.032     -0.807      0.420      -0.089       0.037
C(city_level)[T.4]                                  -0.0559      0.033     -1.709      0.088      -0.120       0.008
C(city_level)[T.5]                                   0.0301      0.063      0.478      0.633      -0.093       0.154
C(gender)[T.M]                                       0.0024      0.017      0.143      0.886      -0.031       0.036
C(gender)[T.U]                                       0.3560      0.198      1.801      0.072      -0.031       0.743
C(age)[T.26-35]                                      0.0853      0.017      5.009      0.000       0.052       0.119
C(age)[T.36-45]                                      0.1220      0.021      5.878      0.000       0.081       0.163
C(age)[T.46-55]                                      0.0842      0.038      2.210      0.027       0.010       0.159
C(age)[T.<=15]                                      -0.1633      0.959     -0.170      0.865      -2.042       1.716
C(age)[T.>=56]                                       0.0777      0.046      1.687      0.092      -0.013       0.168
C(age)[T.U]                                         -0.4551      0.200     -2.270      0.023      -0.848      -0.062
is_plus                                             -0.0592      0.016     -3.648      0.000      -0.091      -0.027
sku_focus_flag                                       1.1450      0.016     71.171      0.000       1.113       1.177
user_day_distinct_skus                              -0.0637      0.002    -39.557      0.000      -0.067      -0.061
====================================================================================================================

In [13]:
model3_repeat = smf.logit(
    base_formula + " + repeat_same_sku_flag + click_cnt",
    data=model_df
).fit(method='lbfgs', maxiter=300)

print(model3_repeat.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:               label_7d   No. Observations:               213050
Model:                          Logit   Df Residuals:                   213023
Method:                           MLE   Df Model:                           26
Date:                Mon, 13 Apr 2026   Pseudo R-squ.:                 0.03790
Time:                        12:19:15   Log-Likelihood:                -82740.
converged:                       True   LL-Null:                       -85999.
Covariance Type:            nonrobust   LLR p-value:                     0.000
====================================================================================================================
                                                       coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------
Intercept                                           -2.1391      0.038    -56.826      0.000      -2.213      -2.065
C(channel, Treatment(reference='app'))[T.mobile]     0.7393      0.040     18.481      0.000       0.661       0.818
C(channel, Treatment(reference='app'))[T.others]     0.4580      0.055      8.305      0.000       0.350       0.566
C(channel, Treatment(reference='app'))[T.pc]         0.4666      0.026     17.784      0.000       0.415       0.518
C(channel, Treatment(reference='app'))[T.wechat]     0.0991      0.027      3.638      0.000       0.046       0.153
C(type)[T.2]                                        -0.4724      0.014    -32.703      0.000      -0.501      -0.444
C(purchase_power)[T.1]                               0.0800      0.060      1.332      0.183      -0.038       0.198
C(purchase_power)[T.2]                              -0.0830      0.028     -2.956      0.003      -0.138      -0.028
C(purchase_power)[T.3]                              -0.1251      0.029     -4.270      0.000      -0.183      -0.068
C(purchase_power)[T.4]                               0.0470      0.053      0.888      0.375      -0.057       0.151
C(purchase_power)[T.5]                               0.4461      0.317      1.409      0.159      -0.175       1.067
C(city_level)[T.1]                                   0.1655      0.029      5.671      0.000       0.108       0.223
C(city_level)[T.2]                                   0.0413      0.028      1.461      0.144      -0.014       0.097
C(city_level)[T.3]                                   0.0378      0.031      1.212      0.226      -0.023       0.099
C(city_level)[T.4]                                  -0.0399      0.032     -1.256      0.209      -0.102       0.022
C(city_level)[T.5]                                   0.1054      0.061      1.720      0.085      -0.015       0.226
C(gender)[T.M]                                      -0.0034      0.017     -0.206      0.837      -0.036       0.029
C(gender)[T.U]                                       0.2283      0.182      1.254      0.210      -0.129       0.585
C(age)[T.26-35]                                      0.1847      0.017     11.126      0.000       0.152       0.217
C(age)[T.36-45]                                      0.2277      0.020     11.293      0.000       0.188       0.267
C(age)[T.46-55]                                      0.1795      0.037      4.855      0.000       0.107       0.252
C(age)[T.<=15]                                      -0.2055      0.919     -0.224      0.823      -2.006       1.595
C(age)[T.>=56]                                       0.1811      0.045      4.051      0.000       0.093       0.269
C(age)[T.U]                                         -0.1878      0.186     -1.011      0.312      -0.552       0.176
is_plus                                             -0.0887      0.016     -5.614      0.000      -0.120      -0.058
repeat_same_sku_flag                                 0.0220      0.023      0.949      0.343      -0.023       0.068
click_cnt                                            0.1189      0.002     63.628      0.000       0.115       0.123
====================================================================================================================

In [14]:
model3_channelmix = smf.logit(
    base_formula + " + user_day_distinct_channels",
    data=model_df
).fit(method='lbfgs', maxiter=300)

print(model3_channelmix.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:               label_7d   No. Observations:               213050
Model:                          Logit   Df Residuals:                   213024
Method:                           MLE   Df Model:                           25
Date:                Mon, 13 Apr 2026   Pseudo R-squ.:                 0.01407
Time:                        12:20:38   Log-Likelihood:                -84789.
converged:                       True   LL-Null:                       -85999.
Covariance Type:            nonrobust   LLR p-value:                     0.000
====================================================================================================================
                                                       coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------
Intercept                                           -1.6591      0.043    -38.739      0.000      -1.743      -1.575
C(channel, Treatment(reference='app'))[T.mobile]     0.6465      0.040     16.105      0.000       0.568       0.725
C(channel, Treatment(reference='app'))[T.others]     0.4488      0.058      7.678      0.000       0.334       0.563
C(channel, Treatment(reference='app'))[T.pc]         0.4108      0.029     14.319      0.000       0.355       0.467
C(channel, Treatment(reference='app'))[T.wechat]     0.0485      0.027      1.796      0.072      -0.004       0.101
C(type)[T.2]                                        -0.5463      0.014    -38.407      0.000      -0.574      -0.518
C(purchase_power)[T.1]                               0.0765      0.059      1.294      0.196      -0.039       0.192
C(purchase_power)[T.2]                              -0.0982      0.028     -3.543      0.000      -0.153      -0.044
C(purchase_power)[T.3]                              -0.1293      0.029     -4.469      0.000      -0.186      -0.073
C(purchase_power)[T.4]                               0.0619      0.052      1.185      0.236      -0.040       0.164
C(purchase_power)[T.5]                               0.4571      0.311      1.469      0.142      -0.153       1.067
C(city_level)[T.1]                                   0.1539      0.029      5.339      0.000       0.097       0.210
C(city_level)[T.2]                                   0.0437      0.028      1.566      0.117      -0.011       0.098
C(city_level)[T.3]                                   0.0420      0.031      1.365      0.172      -0.018       0.102
C(city_level)[T.4]                                  -0.0306      0.031     -0.974      0.330      -0.092       0.031
C(city_level)[T.5]                                   0.0995      0.060      1.645      0.100      -0.019       0.218
C(gender)[T.M]                                       0.0179      0.016      1.100      0.271      -0.014       0.050
C(gender)[T.U]                                       0.2070      0.181      1.143      0.253      -0.148       0.562
C(age)[T.26-35]                                      0.1675      0.016     10.237      0.000       0.135       0.200
C(age)[T.36-45]                                      0.2050      0.020     10.307      0.000       0.166       0.244
C(age)[T.46-55]                                      0.1657      0.037      4.541      0.000       0.094       0.237
C(age)[T.<=15]                                      -0.2085      0.916     -0.228      0.820      -2.004       1.587
C(age)[T.>=56]                                       0.1815      0.044      4.112      0.000       0.095       0.268
C(age)[T.U]                                         -0.1814      0.185     -0.983      0.326      -0.543       0.180
is_plus                                             -0.0823      0.016     -5.279      0.000      -0.113      -0.052
user_day_distinct_channels                          -0.0910      0.023     -4.044      0.000      -0.135      -0.047
====================================================================================================================

In [15]:
models = {
    'model2_base': model2,
    'model3_focus': model3_focus,
    'model3_repeat': model3_repeat,
    'model3_channelmix': model3_channelmix
}

key_vars = [
    "C(channel, Treatment(reference='app'))[T.mobile]",
    "C(channel, Treatment(reference='app'))[T.others]",
    "C(channel, Treatment(reference='app'))[T.pc]",
    "C(channel, Treatment(reference='app'))[T.wechat]",
    "C(type)[T.2]",
    "is_plus",
    "sku_focus_flag",
    "user_day_distinct_skus",
    "repeat_same_sku_flag",
    "click_cnt",
    "user_day_distinct_channels"
]

coef_table = pd.DataFrame({
    name: model.params.reindex(key_vars)
    for name, model in models.items()
})

pval_table = pd.DataFrame({
    name: model.pvalues.reindex(key_vars)
    for name, model in models.items()
})

print('系数表：')
display(coef_table)

print('P值表：')
display(pval_table)

系数表：

,model2_base,model3_focus,model3_repeat,model3_channelmix
"C(channel, Treatment(reference='app'))[T.mobile]",0.624769,0.595735,0.739334,0.646547
"C(channel, Treatment(reference='app'))[T.others]",0.363035,0.558179,0.457951,0.448840
"C(channel, Treatment(reference='app'))[T.pc]",0.358963,0.534599,0.466590,0.410753
"C(channel, Treatment(reference='app'))[T.wechat]",0.044121,0.085749,0.099148,0.048494
C(type)[T.2],-0.547216,-0.431315,-0.472362,-0.546312
is_plus,-0.086010,-0.059153,-0.088677,-0.082254
sku_focus_flag,NaN,1.145007,NaN,NaN
user_day_distinct_skus,NaN,-0.063678,NaN,NaN
repeat_same_sku_flag,NaN,NaN,0.022024,NaN
click_cnt,NaN,NaN,0.118924,NaN
user_day_distinct_channels,NaN,NaN,NaN,-0.091031

P值表：

,model2_base,model3_focus,model3_repeat,model3_channelmix
"C(channel, Treatment(reference='app'))[T.mobile]",1.508267e-55,6.128983e-46,2.963266e-76,2.360350e-58
"C(channel, Treatment(reference='app'))[T.others]",3.675839e-11,4.352498e-22,9.946863e-17,1.617213e-14
"C(channel, Treatment(reference='app'))[T.pc]",3.634312e-44,9.895650e-87,9.393639e-71,1.666612e-46
"C(channel, Treatment(reference='app'))[T.wechat]",1.017004e-01,2.240578e-03,2.750264e-04,7.249115e-02
C(type)[T.2],0.000000e+00,9.392839e-187,1.397566e-234,0.000000e+00
is_plus,3.148799e-08,2.637917e-04,1.977634e-08,1.295398e-07
sku_focus_flag,NaN,0.000000e+00,NaN,NaN
user_day_distinct_skus,NaN,0.000000e+00,NaN,NaN
repeat_same_sku_flag,NaN,NaN,3.427449e-01,NaN
click_cnt,NaN,NaN,0.000000e+00,NaN
user_day_distinct_channels,NaN,NaN,NaN,5.250581e-05

In [17]:
model4_interact = smf.logit(
    "label_7d ~ "
    "C(channel, Treatment(reference='app')) * C(type) + "
    "is_plus + C(purchase_power) + C(city_level) + C(gender) + C(age)",
    data=model_df
).fit(method='lbfgs', maxiter=300)

print(model4_interact.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:               label_7d   No. Observations:               213050
Model:                          Logit   Df Residuals:                   213021
Method:                           MLE   Df Model:                           28
Date:                Mon, 13 Apr 2026   Pseudo R-squ.:                 0.01440
Time:                        13:37:01   Log-Likelihood:                -84760.
converged:                       True   LL-Null:                       -85999.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=================================================================================================================================
                                                                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------------------
Intercept                                                        -1.7340      0.037    -47.335      0.000      -1.806      -1.662
C(channel, Treatment(reference='app'))[T.mobile]                  0.5926      0.048     12.329      0.000       0.498       0.687
C(channel, Treatment(reference='app'))[T.others]                  0.5567      0.078      7.147      0.000       0.404       0.709
C(channel, Treatment(reference='app'))[T.pc]                      0.3180      0.029     10.859      0.000       0.261       0.375
C(channel, Treatment(reference='app'))[T.wechat]                 -0.1119      0.035     -3.197      0.001      -0.181      -0.043
C(type)[T.2]                                                     -0.5896      0.016    -36.946      0.000      -0.621      -0.558
C(purchase_power)[T.1]                                            0.0739      0.059      1.249      0.212      -0.042       0.190
C(purchase_power)[T.2]                                           -0.1023      0.028     -3.690      0.000      -0.157      -0.048
C(purchase_power)[T.3]                                           -0.1328      0.029     -4.591      0.000      -0.190      -0.076
C(purchase_power)[T.4]                                            0.0605      0.052      1.159      0.246      -0.042       0.163
C(purchase_power)[T.5]                                            0.4815      0.310      1.552      0.121      -0.126       1.089
C(city_level)[T.1]                                                0.1539      0.029      5.340      0.000       0.097       0.210
C(city_level)[T.2]                                                0.0423      0.028      1.516      0.129      -0.012       0.097
C(city_level)[T.3]                                                0.0426      0.031      1.382      0.167      -0.018       0.103
C(city_level)[T.4]                                               -0.0312      0.031     -0.993      0.321      -0.093       0.030
C(city_level)[T.5]                                                0.1025      0.060      1.695      0.090      -0.016       0.221
C(gender)[T.M]                                                    0.0169      0.016      1.038      0.299      -0.015       0.049
C(gender)[T.U]                                                    0.2006      0.182      1.105      0.269      -0.155       0.556
C(age)[T.26-35]                                                   0.1656      0.016     10.119      0.000       0.134       0.198
C(age)[T.36-45]                                                   0.2044      0.020     10.274      0.000       0.165       0.243
C(age)[T.46-55]                                                   0.1681      0.036      4.606      0.000       0.097       0.240
C(age)[T.<=15]                                                   -0.2324      0.924     -0.251      0.801      -2.044       1.579
C(age)[T.>=56]                                                    0.1802      0.044      4.080      0.000       0.094       0.267
C(age)[T.U]                                                      -0.1948      0.185     -1.053      0.292      -0.558       0.168
C(channel, Treatment(reference='app'))[T.mobile]:C(type)[T.2]     0.1051      0.085      1.234      0.217      -0.062       0.272
C(channel, Treatment(reference='app'))[T.others]:C(type)[T.2]    -0.3315      0.110     -3.012      0.003      -0.547      -0.116
C(channel, Treatment(reference='app'))[T.pc]:C(type)[T.2]         0.1757      0.060      2.936      0.003       0.058       0.293
C(channel, Treatment(reference='app'))[T.wechat]:C(type)[T.2]     0.3632      0.048      7.559      0.000       0.269       0.457
is_plus                                                          -0.0886      0.016     -5.697      0.000      -0.119      -0.058
=================================================================================================================================

In [18]:
model4_interact_focus = smf.logit(
    "label_7d ~ "
    "C(channel, Treatment(reference='app')) * C(type) + "
    "is_plus + C(purchase_power) + C(city_level) + C(gender) + C(age) + "
    "sku_focus_flag + user_day_distinct_skus",
    data=model_df
).fit(method='lbfgs', maxiter=300)

print(model4_interact_focus.summary())

                           Logit Regression Results
==============================================================================
Dep. Variable:               label_7d   No. Observations:               213050
Model:                          Logit   Df Residuals:                   213019
Method:                           MLE   Df Model:                           30
Date:                Mon, 13 Apr 2026   Pseudo R-squ.:                  0.1053
Time:                        14:14:06   Log-Likelihood:                -76940.
converged:                       True   LL-Null:                       -85999.
Covariance Type:            nonrobust   LLR p-value:                     0.000
=================================================================================================================================
                                                                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------------------------------------
Intercept                                                        -1.6738      0.041    -41.033      0.000      -1.754      -1.594
C(channel, Treatment(reference='app'))[T.mobile]                  0.5998      0.051     11.843      0.000       0.501       0.699
C(channel, Treatment(reference='app'))[T.others]                  0.6219      0.082      7.543      0.000       0.460       0.784
C(channel, Treatment(reference='app'))[T.pc]                      0.4958      0.031     16.070      0.000       0.435       0.556
C(channel, Treatment(reference='app'))[T.wechat]                 -0.0579      0.037     -1.586      0.113      -0.129       0.014
C(type)[T.2]                                                     -0.4708      0.017    -28.404      0.000      -0.503      -0.438
C(purchase_power)[T.1]                                            0.0661      0.062      1.068      0.286      -0.055       0.188
C(purchase_power)[T.2]                                           -0.1108      0.029     -3.820      0.000      -0.168      -0.054
C(purchase_power)[T.3]                                           -0.0864      0.030     -2.853      0.004      -0.146      -0.027
C(purchase_power)[T.4]                                            0.0162      0.055      0.296      0.767      -0.091       0.123
C(purchase_power)[T.5]                                            0.2214      0.324      0.684      0.494      -0.413       0.856
C(city_level)[T.1]                                                0.1013      0.030      3.363      0.001       0.042       0.160
C(city_level)[T.2]                                                0.0204      0.029      0.702      0.483      -0.037       0.078
C(city_level)[T.3]                                               -0.0242      0.032     -0.753      0.451      -0.087       0.039
C(city_level)[T.4]                                               -0.0555      0.033     -1.696      0.090      -0.120       0.009
C(city_level)[T.5]                                                0.0326      0.063      0.517      0.605      -0.091       0.156
C(gender)[T.M]                                                    0.0013      0.017      0.077      0.938      -0.032       0.035
C(gender)[T.U]                                                    0.3685      0.196      1.875      0.061      -0.017       0.754
C(age)[T.26-35]                                                   0.0845      0.017      4.964      0.000       0.051       0.118
C(age)[T.36-45]                                                   0.1217      0.021      5.862      0.000       0.081       0.162
C(age)[T.46-55]                                                   0.0856      0.038      2.246      0.025       0.011       0.160
C(age)[T.<=15]                                                   -0.2120      0.975     -0.217      0.828      -2.124       1.700
C(age)[T.>=56]                                                    0.0760      0.046      1.648      0.099      -0.014       0.166
C(age)[T.U]                                                      -0.4822      0.199     -2.419      0.016      -0.873      -0.091
C(channel, Treatment(reference='app'))[T.mobile]:C(type)[T.2]    -0.0066      0.090     -0.073      0.942      -0.182       0.169
C(channel, Treatment(reference='app'))[T.others]:C(type)[T.2]    -0.0922      0.115     -0.801      0.423      -0.318       0.133
C(channel, Treatment(reference='app'))[T.pc]:C(type)[T.2]         0.1586      0.063      2.536      0.011       0.036       0.281
C(channel, Treatment(reference='app'))[T.wechat]:C(type)[T.2]     0.3285      0.050      6.571      0.000       0.230       0.426
is_plus                                                          -0.0614      0.016     -3.785      0.000      -0.093      -0.030
sku_focus_flag                                                    1.1437      0.016     71.063      0.000       1.112       1.175
user_day_distinct_skus                                           -0.0637      0.002    -39.581      0.000      -0.067      -0.061
=================================================================================================================================